name: Comment on Every Pull Request

on: [push, pull_request]

# NOTE: This is possibly insecure; it allows Dependabot to comment on a PR, the point of this run.
# @see: https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/
permissions:
  pull-requests: write

jobs:
  add-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find Pull Request
        id: find-pr
        uses: ./ # run against self
        with:
          failIfNotFound: ${{ github.event_name == 'pull_request' }} # Fail for a PR, not for a push

      - name: Comment on the found Pull Request
        if: steps.find-pr.outputs.number != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment # basically a key
          number: ${{ steps.find-pr.outputs.number }}
          message: |
            :tada: I added a comment!

             - number: ${{ steps.find-pr.outputs.number }}
             - title: ${{ steps.find-pr.outputs.title }}
             - body: ${{ steps.find-pr.outputs.body }}
             - url: ${{ steps.find-pr.outputs.url }}
